#
#   Date: 2015-07-20 16:46:35 +0100 (Mon, 20 Jul 2015)
#
#  vim:ts=2:sw=2:et
#
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    name: prometheus
  template:
    metadata:
      labels:
        name: prometheus
    spec:
      containers:
      - name: prometheus-k8s
        image: gambol99/prometheus-k8s
        args:
          - -config=/etc/prometheus/targets.d
          - -bearer-token-file=/etc/tokens/node-register.token
          - -api=10.101.0.1
          - -api-protocol=https
          - -insecure=true
          - -logtostderr=true
          - -v=3
          - -nodes=false
        volumeMounts:
        - name: targets
          mountPath: /etc/prometheus/targets.d
        - name: tokens
          mountPath: /etc/tokens/node-register.token
      - name: prometheus-fleet
        image: gambol99/prometheus-fleet:0.0.1
        args:
          - -config=/etc/prometheus/targets.d/fleet-nodes.yml
          - -job=compute;role=kubernetes;9100
          - -job=etcd;role=etcd;9100
          - -job=ceph_store;role=ceph_store;9100
          - -job=ceph_monitor;role=ceph_monitor;9100
          - -all
          - -logtostderr=true
          - -v=3
        volumeMounts:
        - name: fleet
          mountPath: /var/run/fleet.sock
        - name: targets
          mountPath: /etc/prometheus/targets.d
      - name: prometheus
        image: gambol99/prometheus
        ports:
        - containerPort: 9090
        args:
          - -config.file=/etc/prometheus/prometheus.yml
          - -storage.local.path=/prometheus
          - -web.console.libraries=/etc/prometheus/console_libraries
          - -web.console.templates=/etc/prometheus/console
        volumeMounts:
        - name: targets
          mountPath: /etc/prometheus/targets.d
      imagePullPolicy: Always
      volumes:
      - name: tokens
        hostPath:
          path: /run/kube-kubelet/node-register.token
      - name: targets
        source:
          emptyDir: {}
      - name: fleet
        hostPath:
          path: /var/run/fleet.sock
